version: '3'
services:
  golang:
    container_name: acme_go
    image: golang:1.12-alpine
    volumes:
      - '.:/go/src/app/'
    working_dir: '/go/src/app'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    restart: always